use serde::{Deserialize, Serialize};
use std::env;
use tracing::{info, warn};

use crate::state::trivia::{TriviaQuestion, TriviaStyle};

#[derive(Serialize)]
struct OllamaOptions {
    temperature: f32,
}

#[derive(Serialize)]
struct OllamaGenerateRequest {
    model: String,
    prompt: String,
    stream: bool,
    format: String,
    options: OllamaOptions,
}

#[derive(Deserialize)]
struct OllamaGenerateResponse {
    response: String,
}

pub(crate) async fn load_trivia_questions(
    topic: &str,
    num_questions: u8,
    style: TriviaStyle,
    model: &str,
) -> Result<Vec<TriviaQuestion>, String> {
    let ollama_host =
        env::var("OLLAMA_HOST").unwrap_or_else(|_| "http://localhost:11434".to_string());
    let url = format!("{}/api/generate", ollama_host);

    let prompt = match style {
        // This formatting works, could also use the format parameter provided by Ollama
        TriviaStyle::MultipleChoice => {
            format!(
                "You are a professional trivia generator. Generate exactly {} challenging and interesting multiple-choice trivia questions about the topic '{}'. \
                Each question MUST have exactly 4 choices, and a correct_answer which MUST be exactly one of the choices. \
                Do not prefix choices with letters like A, B, C, D. Just provide the raw text. \
                Your response must be a single, raw valid JSON array. Do not wrap in markdown or any other tags. \
                The JSON schema is: \
                [ \
                  {{ \
                    \"question\": \"Question text?\", \
                    \"choices\": [\"choice 1\", \"choice 2\", \"choice 3\", \"choice 4\"], \
                    \"correct_answer\": \"choice 2\" \
                  }} \
                ]",
                num_questions, topic
            )
        }
        TriviaStyle::ShortAnswer => {
            format!(
                "You are a professional trivia generator. Generate exactly {} challenging and interesting trivia questions about the topic '{}'. \
                Each question MUST have a direct, single short-answer (typically 1-3 words). \
                Your response must be a single, raw valid JSON array. Do not wrap in markdown or any other tags. \
                The JSON schema is: \
                [ \
                  {{ \
                    \"question\": \"Question text?\", \
                    \"correct_answer\": \"Answer\" \
                  }} \
                ]",
                num_questions, topic
            )
        }
    };

    info!(url=%url, model=%model, topic=%topic, "Sending generation request to Ollama");

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(60))
        .build()
        .map_err(|e| format!("Failed to build HTTP client: {}", e))?;

    let req_body = OllamaGenerateRequest {
        model: model.to_string(),
        prompt,
        stream: false,
        format: "json".to_string(),
        options: OllamaOptions { temperature: 1.0 },
    };

    let response = client
        .post(&url)
        .json(&req_body)
        .send()
        .await
        .map_err(|e| format!("Ollama connection error: {}. Make sure Ollama is running at {} and model '{}' is pulled.", e, ollama_host, model))?;

    if !response.status().is_success() {
        let status = response.status();
        let err_text = response.text().await.unwrap_or_default();
        warn!(status=?status, err=%err_text, "Ollama returned error status");
        return Err(format!(
            "Ollama server returned error {}: {}",
            status, err_text
        ));
    }

    let gen_response = response
        .json::<OllamaGenerateResponse>()
        .await
        .map_err(|e| format!("Failed to parse Ollama envelope: {}", e))?;

    info!("Received response from Ollama. Parsing trivia questions JSON...");

    // Deserialize the JSON array of questions from the response field
    let mut questions: Vec<TriviaQuestion> = serde_json::from_str(&gen_response.response)
        .map_err(|e| {
            warn!(response=%gen_response.response, error=%e, "Failed to parse trivia questions JSON");
            format!("Invalid trivia JSON structure generated by model: {}. Raw response: {}", e, gen_response.response)
        })?;

    // Ensure multiple choice questions have exactly 4 choices and choices contains correct_answer
    if style == TriviaStyle::MultipleChoice {
        for (i, q) in questions.iter_mut().enumerate() {
            if let Some(ref choices) = q.choices {
                if choices.len() != 4 {
                    return Err(format!(
                        "Question {} has invalid choices count (expected 4, got {})",
                        i + 1,
                        choices.len()
                    ));
                }
                if !choices.contains(&q.correct_answer) {
                    return Err(format!(
                        "Question {} correct answer '{}' is not among the choices {:?}",
                        i + 1,
                        q.correct_answer,
                        choices
                    ));
                }
            } else {
                return Err(format!(
                    "Question {} is missing choices for multiple-choice style",
                    i + 1
                ));
            }
        }
    } else {
        // For ShortAnswer, enforce choices to be None
        for q in questions.iter_mut() {
            q.choices = None;
        }
    }

    info!(count=%questions.len(), "Successfully loaded trivia questions");
    Ok(questions)
}
